import fs from 'fs';
import path from 'path';
import type { Plugin } from 'vite';
import { appTheme } from './App.theme';

export const themePlugin = (): Plugin => ({
  name: 'theme-css-generator',
  buildStart() {
    const flatten = (
      obj: object = appTheme,
      path: string[] = [],
      res: Record<string, string> = {},
    ) => {
      for (const [key, value] of Object.entries(obj)) {
        const nextPath = [...path, key];
        if (
          value &&
          typeof value === 'object' &&
          !Array.isArray(value)
        ) {
          flatten(value, nextPath, res);
        } else {
          res[`--${nextPath.join('-')}`] = value;
        }
      }
      return res;
    };

    const css = `/* AUTOGENERATED */\n:root {\n${Object.entries(
      flatten(),
    )
      .map(([k, v]) => `  ${k}: ${v};`)
      .join('\n')}\n}\n`;

    const out = path.resolve(
      __dirname,
      'styles/theme-vars.css',
    );
    fs.writeFileSync(out, css, 'utf8');
  },
});
